Refresh is now being called in update request
Plazide/node-twitch pull request #31
Opened 2021-11-07 00:41 UTC by HetIsJoey

2021-11-07 11:53 UTC, Plazide requested changes
Hi, thanks for contributing.

Although... you are missing the curly brackets after the `if` statement. As it is now, only the refresh will happen if the `status` is `401` and not the post request. 

Add the two statements in brackets, and then it's good.

2021-11-07 14:12 UTC, HetIsJoey commented
Should be good now 👍🏻 , Sorry about that :)

2021-11-10 08:44 UTC, Plazide reviewed
No worries. It looks good now.

I will run tests and then publish.

Thanks for contributing!

2021-11-10 08:45 UTC, Plazide approved these changes

2021-12-07 17:19 UTC, merged